fix(eslint-plugin): [sort-ngmodule-metadata-arrays] do not sort deps property
angular-eslint/angular-eslint pull request #1001
Opened 2022-05-22 09:37 UTC by dhhyi

The rule currently sorts the `deps` property of factory providers which scrambles the order the arguments are given to the function.

New behavior: `deps` property is excluded from selector.

Closes #703

2022-06-05 17:29 UTC, JamesHenry approved these changes
Thanks @dhhyi!

2022-06-05 17:46 UTC, JamesHenry requested changes
Sorry you just need to update the rule docs to include this new test case:

Just run:

```sh
yarn update-rule-docs
```

and commit the result

2022-06-05 21:10 UTC, dhhyi commented
> Just run: yarn update-rule-docs and commit the result

Done, amended and also rebased on latest master 👍

2022-06-06 11:03 UTC, JamesHenry approved these changes

2022-06-06 11:04 UTC, merged