feat(eslint-plugin-template): accessibility-tabindex-no-positive
angular-eslint/angular-eslint pull request #128
Opened 2020-09-08 19:15 UTC by andrefilimono

Rewritten version of the `template-accessibility-tabindex-no-positive` rule from Codelyzer.

Looking forward to hearing your feedback.

2020-09-08 19:21 UTC, JamesHenry requested changes
Thanks so much!

Given we have this chance for fresh perspective, I think we could rename this to just: “no-positive-tabindex”

- having the no- first is more in keeping with eslint conventions
- the fact this rule exists due to accessibility concerns can be expressed through documentation, I don’t think it needs to be in the rule name

WDYT?

2020-09-08 19:55 UTC, andrefilimono commented
> Thanks so much!
> 
> Given we have this chance for fresh perspective, I think we could rename this to just: “no-positive-tabindex”
> 
> * having the no- first is more in keeping with eslint conventions
> * the fact this rule exists due to accessibility concerns can be expressed through documentation, I don’t think it needs to be in the rule name
> 
> WDYT?

Yeah, that's definitely a better name for the rule. Thanks!

2020-09-19 10:41 UTC, JamesHenry approved these changes

2020-09-19 10:42 UTC, merged

2020-09-19 10:42 UTC, JamesHenry commented
Thanks again for this!