feat(eslint-plugin-template): [self-closing-tags] add rule
angular-eslint/angular-eslint pull request #1322
Opened 2023-03-10 14:22 UTC by aleesaan

Implements the feature proposed in [this discussion](https://github.com/angular-eslint/angular-eslint/discussions/1318).

Let me know If there's a better way to check that an element has no content, and thanks for the awesome plugin!

2023-04-05 15:29 UTC, JamesHenry requested changes
Thanks a lot for this @aleesaan! Please see the comments inline

2023-04-05 15:29 UTC, JamesHenry commented on packages/utils/src/eslint-plugin-template/native-elements.ts
Please use the existing `getDomElements()` utility that we have and do not introduce a new list for us to maintain separately.

You can have a look in https://github.com/angular-eslint/angular-eslint/blob/6abcc3ab0d3000d00ab668d2f6776e0f851b0a41/packages/eslint-plugin-template/src/rules/accessibility-role-has-required-aria.ts for precedent on how to select native elements (and here you want to do the inverse, and only select non-native)

2023-04-05 15:29 UTC, JamesHenry commented on packages/eslint-plugin-template/tests/rules/self-closing-tags/cases.ts
> +  '<img />',
Please add a non self-closing native element example

2023-04-05 15:29 UTC, JamesHenry commented on packages/eslint-plugin-template/src/rules/self-closing-tags.ts
> +      Element$1({
Please see comment about applying the filter of non-native elements in the selector

2023-04-05 15:29 UTC, JamesHenry commented on packages/eslint-plugin-template/docs/rules/self-closing-tags.md
> +# `@angular-eslint/template/self-closing-tags`
To match existing conventions, please go for `prefer-self-closing-tags` as the rule name

2023-04-06 20:27 UTC, aleesaan commented on packages/utils/src/eslint-plugin-template/native-elements.ts
Thank you so much for the feedback! I was in fact looking for this kind of suggestions 😅 I pushed the fixes, let me know how it looks.

2023-06-01 08:18 UTC, JamesHenry commented
Thanks a lot @aleesaan after that one final change and syncing up with the latest this is ready to merge!

2023-06-01 09:23 UTC, aleesaan commented
Fixed the last things and rebased! Let me know if it's all looking food :)

2023-06-03 14:44 UTC, JamesHenry approved these changes

2023-06-03 14:49 UTC, merged