fix(eslint-plugin-template): fix fixer of inline templates
angular-eslint/angular-eslint pull request #1472
Opened 2023-08-10 18:05 UTC by json-derulo

Currently, the rule fixer does not return correct results for inline templates. It applies to all template rules with a fixer, see https://github.com/angular-eslint/angular-eslint/issues/1464#issuecomment-1673008115. This is fixed by this PR.

Closes #1464 

Note: I wanted to add some tests, but I'm not sure where to start

2023-08-19 18:24 UTC, JamesHenry requested changes
Thanks @json-derulo!

When you say you weren't sure where to start... Did you consider adding the cases you reported to the relevant rule's test cases?

You just need to look at the existing tests, duplicate one or more and amend.

We will definitely want to capture your findings as tests before proceeding

2023-08-19 19:26 UTC, json-derulo commented
@JamesHenry added a test case

2023-08-19 19:28 UTC, JamesHenry commented
@json-derulo I meant more capturing the real experience you were having using rules e.g. here https://github.com/angular-eslint/angular-eslint/issues/1464#issuecomment-1673008115

2023-08-22 16:40 UTC, json-derulo commented
@JamesHenry I am a bit stuck trying to add tests for the real cases. I have tried to setup test cases with the `RuleTester`. When I use parser `@typescript-eslint/parser`, I'm always getting the following error:

>  Error while loading rule: You have used a rule which requires '@angular-eslint/template-parser' to be used as the 'parser' in your ESLint config.

I have tried to extend from `@angular-eslint/template/process-inline-templates`, use processor `@angular-eslint/template/extract-inline-html`, plugin `@angular-eslint/template` and several combinations of those. The error persists.

When I use parser `@angular-eslint/template-parser` no errors are reported for the invalid cases, it seems like it cannot understand the TypeScript syntax.

Do you have any other idea how I could test this?

2023-08-22 17:27 UTC, JamesHenry commented
Yes sorry I think I was skipping some relevant complexity here, it probably isn’t a good fit for the unit tests, it would be better as an integration test.

I’m on my phone and thinking out loud but I think we could add a relevant file to the generated fixture in one of the existing integration tests and snapshot it before and after applying fixing. 

If you have time to play around with this idea in the next few days then that’s great, otherwise I can take a proper look this weekend sometime

2023-08-23 18:21 UTC, json-derulo commented
@JamesHenry thanks for your input, I think I figured it out by myself. I've implemented an integration test which generates a fresh Angular Workspace and runs Angular ESLint Add schematics. Afterwards, a new test component file is generated with the test cases. I excluded the `prefer-self-closing-tags` rule there because it's not part of the recommended rule set and would require additional steps. Finally, the lint fixer is executed, and the resulting file content is checked against a snapshot.

Not sure why the CI is failing, on my machine the integration tests succeed. Also the failure is related to a different integration test which was not changed.

2023-09-06 16:59 UTC, json-derulo commented
@JamesHenry after rebasing the latest changes from the main branch, CI is green now. Could you have a look again to the changes of this PR?

2023-09-16 17:26 UTC, JamesHenry approved these changes
Great work, thank you @json-derulo!

2023-09-16 17:27 UTC, merged