feat(eslint-plugin-template): allow `alias` option in [use-track-by-function]
angular-eslint/angular-eslint pull request #1497
Opened 2023-08-22 20:10 UTC by arturovt

This commit adds an `alias` option to the `use-track-by-function` rule, allowing the specification of a list of properties that should be treated similarly to `ngForTrackBy`.

Closes #1323

2023-09-16 17:34 UTC, JamesHenry commented on packages/eslint-plugin-template/jest.config.ts
Why did this require changing a jest config?

2023-09-16 17:38 UTC, JamesHenry requested changes
Thanks @arturovt! Comments inline

2023-09-16 17:38 UTC, JamesHenry commented on packages/eslint-plugin-template/tests/rules/use-track-by-function/cases.ts
Please add a full ng-template example of using the custom directive (both a passing and failing case, like we have elsewhere in this file

2023-09-16 18:47 UTC, arturovt commented on packages/eslint-plugin-template/jest.config.ts
This is causing warnings to appear in the console, and these warnings are overlapping everything I logged with `console.log`.

2023-09-16 18:47 UTC, arturovt commented on packages/eslint-plugin-template/tests/rules/use-track-by-function/cases.ts
Updated.

2023-09-17 10:27 UTC, JamesHenry commented
You need to run `yarn update-rule-docs` please

2023-10-15 10:34 UTC, JamesHenry approved these changes
Thanks a lot @arturovt!

2023-10-15 10:34 UTC, merged