feat(eslint-plugin): add rules for standalone pipes and directives
angular-eslint/angular-eslint pull request #1627
Opened 2023-11-19 00:02 UTC by csvn

Adds rules for checking `@Directive` and `@Pipe` for being `standalone` in addition to the existing `@Component` rule.

An alternative would be to add options to the current `prefer-standalone-component` for also checking pipe/directive, but was afraid it might be confusing to keep check the other decorators for the existing rule.

2024-01-06 20:03 UTC, JamesHenry requested changes
Hi @csvn I'm sorry for the delay in getting back to you on this one.

I think what might be best overall here is to create a new rule: `prefer-standalone` which applies checks for all the things (as really people should either be doing all or nothing I think).

At the same time we deprecate the `prefer-standalone-component` rule and look to remove it in the next major for clarity

2024-01-09 08:14 UTC, csvn commented
I would be fine with that. I'll update this MR soon based on that feedback.

2024-02-07 13:07 UTC, csvn commented on packages/eslint-plugin/src/rules/prefer-standalone.ts
> +      (type: DecoratorTypes) => (node: TSESTree.Decorator) => {
The contents of this function is the same as for [prefer-standalone-component](https://github.com/angular-eslint/angular-eslint/blob/ee4ebf2ab381164eebf889b131c15f15a93a9693/packages/eslint-plugin/src/rules/prefer-standalone-component.ts#L34), with the addition of turning it into a factory function and passing in the decorator `type` for the messageID data property.

2024-02-07 13:07 UTC, csvn commented on packages/eslint-plugin/tests/rules/prefer-standalone/cases.ts
> +export const valid = [
The `valid` & `invalid` test cases here are the same as for `prefer-standalone-component` + new cases for `@Pipe` and `@Directive` (taken from prior commits).

2024-02-07 13:08 UTC, csvn commented
@JamesHenry I think I've addressed your feedback now, and that this PR is ready for review. Sorry for it taking a while for me to get back to this one.

2024-03-15 21:20 UTC, merged

2024-03-15 21:20 UTC, JamesHenry commented
Thanks so much @csvn!