fix(eslint-plugin-template): handle i18n tags on structural direcives
angular-eslint/angular-eslint pull request #1662
Opened 2023-12-06 15:36 UTC by mattlewis92

Fixes a regression caused by https://github.com/angular-eslint/angular-eslint/pull/1257 where i18n attributes on structural directives are not propertly detected. The fix is to tighten the `isTemplate` helper to only check for `ng-template` nodes and not all template nodes which are created by using a structural directive.

2023-12-06 15:36 UTC, mattlewis92 commented on packages/eslint-plugin-template/src/rules/i18n.ts
> +  return ast instanceof TmplAstTemplate && ast.tagName === 'ng-template';
This is the actual fix, the rest is just a refactor to rename the method to something better.

2024-01-06 20:23 UTC, JamesHenry requested changes
Thanks! Ready to be reconciled with latest main

2024-01-08 10:33 UTC, mattlewis92 commented
> Thanks! Ready to be reconciled with latest main

Done!

2024-01-08 13:06 UTC, JamesHenry approved these changes

2024-01-08 13:06 UTC, merged

2024-01-08 13:06 UTC, JamesHenry commented
THanks @mattlewis92