feat(eslint-plugin-template): [i18n] add allowMarkupInContent option
angular-eslint/angular-eslint pull request #1795
Opened 2024-05-01 23:36 UTC by m-akinc

Fixes #930

Added `allowMarkupInContent` option for `i18n` rule. Option defaults to `true` to maintain backwards compatibility. Setting to `false` causes rule violation whenever an element with the `i18n` attribute has HTML markup in its content.

Note that due to the way the AST parser handles ICUs (i.e. it escapes any markup in cases so that they are strings), we cannot report violations for markup inside the ICU cases.

2024-05-15 17:33 UTC, m-akinc commented
@JamesHenry There haven't been any comments or review since I put this up a couple weeks ago. Just wanted to ping someone to make sure it isn't overlooked.

2024-05-21 20:19 UTC, JamesHenry requested changes
Thanks @m-akinc!

I would prefer it if no existing tests were modified by this PR to prove that this change is backwards compatible. Please can you make the necessary updates?

2024-05-22 12:02 UTC, JamesHenry approved these changes

2024-05-22 12:02 UTC, merged

2024-05-22 12:03 UTC, JamesHenry commented
Thank you @m-akinc!