feat: support eslint.config.mjs and eslint.config.cjs
angular-eslint/angular-eslint pull request #1968
Opened 2024-08-07 16:01 UTC by JasonWeinzierl

ESLint supports `mjs` and `cjs` file extensions for their flat configs: https://eslint.org/docs/latest/use/configure/configuration-files.  It would be nice to support particularly `mjs` configs so users can use `import`/`export` ESM syntax.

2024-08-12 15:52 UTC, JamesHenry requested changes
@JasonWeinzierl Thank you but this is incomplete, because the logic for adding extends to newly created projects within a workspace would need to handle this. I would also want to see e2e test coverage for something like to cover a realistic user experience. You can take a look at the existing fixtures for inspiration if you are happy to take that on, otherwise this will need to wait until I have some time.

Please also be aware that recently .ts extension support was added behind a flag... So it might be better to tackle all non .js containing commonjs cases at once instead of this workaround.

2024-09-15 09:28 UTC, JamesHenry commented
@JasonWeinzierl Following up on this one please

2024-10-03 06:25 UTC, hakimio commented
@JasonWeinzierl are you planning to finish this PR?

2024-10-03 17:51 UTC, JasonWeinzierl commented
> @JasonWeinzierl are you planning to finish this PR?

My apologies.  This PR came from a patch to get it working for myself.  I have not had time to look into the requested changes, nor do I feel I have a deep enough understanding of this project to do it properly.

2024-10-03 17:51 UTC, closed without merging