feat(eslint-plugin): add options for custom ID and default value validation
angular-eslint/angular-eslint pull request #2186
Opened 2024-12-18 10:41 UTC by tcorral

Added two more options to report errors if:
- Custom ID is not present
- Custom ID is present but it doesn't follow the allowed pattern
- Default value is not provided

Change in details:
- Added new configuration options and error messages for reporting.
- Create and use a `validate` function that receives the input string and a type to validate optionally it can receive a pattern to validate custom id.
- The core of the `validate` function is a regular expression with named group, I have followed how Angular manages metadata when using `$localize`
- Added new valid and invalid tests cases to cover the changes.

New config after changes:
- Added `requireCustomId` - `boolean` - default is `false`
- Added `requireDefaultValue` - `boolean` - default is `false`
- Added `boundTextAllowedPattern` - `string` - No default value. It expects to get a string that can be converted to regular expression to test custom id. I have used the same name that already exists in `@angular-eslint/template-parser`.

2025-01-13 07:28 UTC, tcorral commented
Any update on this PR?

2025-01-23 10:38 UTC, JamesHenry requested changes
Thanks a lot @tcorral, some feedback and open questions

2025-01-23 10:38 UTC, JamesHenry commented on packages/eslint-plugin/package.json
> +  "version": "19.1.0",
Revert this, versioning is automated and does not happen through imperative updates to version fields, and all packages are released together so changing only one package would never be the right thing to do.

2025-01-23 10:38 UTC, JamesHenry commented on packages/eslint-plugin/src/rules/require-localize-metadata.ts
>  const STYLE_GUIDE_LINK_COMMON_PREPARE = `${STYLE_GUIDE_LINK}-common-prepare`;
This link no longer seems to be correct at all (I think the new one is https://angular.dev/guide/i18n/prepare?) so let's please fix it as part of this PR so that all the various errors have reasonable links.

I discovered this when trying to verify the ones you added (which should be here now I believe https://angular.dev/guide/i18n/manage-marked-text)

2025-01-23 10:38 UTC, JamesHenry commented on packages/eslint-plugin/src/rules/require-localize-metadata.ts
> +          boundTextAllowedPattern: {
I don't think this is very clear that it relates to custom ID.

I think something like this would be much clearer:

```json
{
  "@angular-eslint/require-localizae-metadata": [
     "error",
     {
       "requireCustomId": true,
       "requireCustomIdMatchingPattern": "custom_id"
     }
  ]
}
```

We potentially could then take it a step further and dynamically default `requireCustomId` to true when `requireCustomIdMatchingPattern`?

2025-01-23 10:38 UTC, JamesHenry commented on packages/eslint-plugin/src/rules/require-localize-metadata.ts
> +          boundTextAllowedPattern: {
With that said, I am not super clear on the examples you have of:

```
boundTextAllowedPattern:
          '^(?<lib>.[^\\.]*)\\.(?<component>.[^\\.]*)\\.(?<tag>.[^\\.]*)\\.(?<attribute>.[^\\.]*)?\\.(?<name>.[^\\.]*).$',
```

Are all of the sections potentially applicable to just the custom ID in practice? (I am not somebody who has ever leveraged the i18n feature personally). Maybe you could please give some real world examples?

2025-02-21 11:19 UTC, tcorral commented on packages/eslint-plugin/src/rules/require-localize-metadata.ts
> +          boundTextAllowedPattern: {
To answer your last question:

This is an example of pattern on which you have a more verbose pattern that can be used for more people to understand where the translation is used and that can help to identify and avoid duplicated ids.

Here you have an example of a custom id that matches this regular expression: 'cards-management.form-details.input.placeholder.title'

This is just an example and can be overriden, but I thought it could be interesting to have an example.

2025-02-21 11:21 UTC, tcorral commented on packages/eslint-plugin/src/rules/require-localize-metadata.ts
> +          boundTextAllowedPattern: {
> With that said, I am not super clear on the examples you have of:
> 
> ```
> boundTextAllowedPattern:
>           '^(?<lib>.[^\\.]*)\\.(?<component>.[^\\.]*)\\.(?<tag>.[^\\.]*)\\.(?<attribute>.[^\\.]*)?\\.(?<name>.[^\\.]*).$',
> ```
> 
> Are all of the sections potentially applicable to just the custom ID in practice? (I am not somebody who has ever leveraged the i18n feature personally). Maybe you could please give some real world examples?

I thought that it could be interesting to give some example to the developers to avoid duplicated custom ids and also to provide some more information about where the custom id is used.

Here you have an example of a custom id matching the regular expression: "cards-management.card-details-form.input.placeholder.remaining-credit"

2025-02-21 11:23 UTC, tcorral commented on packages/eslint-plugin/src/rules/require-localize-metadata.ts
> +          boundTextAllowedPattern: {
> I don't think this is very clear that it relates to custom ID.
> 
> I think something like this would be much clearer:
> 
> ```json
> {
>   "@angular-eslint/require-localizae-metadata": [
>      "error",
>      {
>        "requireCustomId": true,
>        "requireCustomIdMatchingPattern": "custom_id"
>      }
>   ]
> }
> ```
> 
> We potentially could then take it a step further and dynamically default `requireCustomId` to true when `requireCustomIdMatchingPattern`?

I have changed the name of the property to the one you have suggested.

How would you like to dynamically default `requireCustomId` to true?

2025-02-21 11:24 UTC, tcorral commented on packages/eslint-plugin/src/rules/require-localize-metadata.ts
>  const STYLE_GUIDE_LINK_COMMON_PREPARE = `${STYLE_GUIDE_LINK}-common-prepare`;
Updated.

2025-02-21 11:24 UTC, tcorral commented on packages/eslint-plugin/package.json
> +  "version": "19.1.0",
Reverted.

2025-02-21 11:25 UTC, tcorral commented on packages/eslint-plugin/tests/rules/require-localize-metadata/cases.ts
> +        char: '~',
I found it was needed for the tests to pass green.

2025-03-02 11:57 UTC, JamesHenry commented on packages/eslint-plugin/src/rules/require-localize-metadata.ts
> +          boundTextAllowedPattern: {
You changed the messageId but not the option which is the more prominent user-facing thing that I was concerned about.

For a dynamic default, you could just not specify it on the schema and apply it within the rule implementation at runtime, right?

2025-03-02 11:58 UTC, JamesHenry commented on packages/eslint-plugin/package.json
> -  "version": "19.1.0",
This shouldn't be here at all, there should not be any changes to package.json files in this PR

2025-03-02 12:00 UTC, JamesHenry commented on packages/eslint-plugin/tests/rules/require-localize-metadata/cases.ts
> +        char: '~',
I'd need to look at the test and your changes in detail, but I probably suggests a breaking change was introduced with this PR which we would want to avoid. Maybe something needs to be off by default? If you could at least please get to the bottom of why this change was needed we could then discuss if the change of behaviour is minor/objectively desired enough for it to go in as is, otherwise it might need to be worked around and changed in a major

2025-03-22 09:02 UTC, JamesHenry commented
@tcorral Would you like some help in finalizing this one?

2025-03-31 11:50 UTC, tcorral commented
@JamesHenry yes, please.

2025-05-08 13:21 UTC, JamesHenry commented
Ok I should be able to find some time in the next couple of weeks

2025-05-16 11:40 UTC, igord commented
@JamesHenry please check this PR adding the same functionality but with slightly different approach

2025-06-01 08:02 UTC, JamesHenry commented
Closing in favour of #2430

2025-06-01 08:02 UTC, closed without merging