refactor(eslint-plugin): component-max-inline-declarations no longer …
angular-eslint/angular-eslint pull request #391
Opened 2021-04-03 22:37 UTC by rafaelss95

…accept negative values

BREAKING CHANGE.

As discussed in https://github.com/angular-eslint/angular-eslint/pull/313#discussion_r565800014, `component-max-inline-declarations` currently accepts negative values as input, but we just ignore this and use a default value instead.

With these changes, this rule no longer accept negative values.

2021-04-06 08:18 UTC, JamesHenry commented
@rafaelss95 So what happens after this change if someone has set a negative value today?

2021-04-06 23:06 UTC, rafaelss95 commented
> So what happens after this change if someone has set a negative value today? 

The linter won't run properly, because the rule no longer accepts a negative value in its schema.

> Is there a recommended change/automated migration we can do for them?

We could perhaps create a migration to put the default values instead. That's the current behavior: if you pass a negative value, the rule ignores it and assume the default one.
A question: do we have any migration like this in repo already?

2021-04-11 12:57 UTC, JamesHenry requested changes
I've changed the base branch to be the v3 branch, please rebase against its latest changes - that is where the current crop of breaking changes are being collected together.

Yes, on that branch, and previously for v2 I provided migration schematics, please add to the v3 one with the logic to update people's eslint configs if they are explicitly using negative numbers

2021-04-13 02:51 UTC, rafaelss95 commented on packages/schematics/src/migrations/update-3-0-0/update-3-0-0.ts
> +  );
```json
**Before**:
"@angular-eslint/component-max-inline-declarations": [
  "error",
  {
    "animations": -1,
    "styles": 3,
    "template": 10
  }
],
```

**After**:
```json
"@angular-eslint/component-max-inline-declarations": [
  "error",
  {
    "styles": 3,
    "template": 10
  }
],
```

That's what we do currently: ignore the negative value and assume the default one.

2021-04-13 02:54 UTC, rafaelss95 commented on packages/schematics/src/migrations/update-3-0-0/update-3-0-0.ts
> +    rules?.['component-max-inline-declarations'],
Do we need to specify it as `"@angular-eslint/component-max-inline-declarations"` or it just work as is? I just saw that in v2 migration, you used `use-pipe-decorator`...

2021-04-13 03:20 UTC, rafaelss95 commented
While seeing the v2 migration, I found you used `use-pipe-decorator` there (https://github.com/angular-eslint/angular-eslint/blob/c80df75267f7f66db35035b12b7e40b253494118/packages/schematics/src/migrations/update-2-0-0/update-2-0-0.ts#L88), but shouldn't it be `@angular-eslint/use-pipe-decorator`?

2021-04-17 12:06 UTC, JamesHenry commented
@rafaelss95 Great catch, yes it should

2021-04-17 12:08 UTC, JamesHenry approved these changes
Thanks! Nice work on the migration

2021-04-17 12:09 UTC, merged