refactor(utils): change return type of fixer utilities
angular-eslint/angular-eslint pull request #518
Opened 2021-05-28 18:04 UTC by rafaelss95

Currently, if it isn't possible to determine a fix in utility functions, we simply return an empty `array` (`TSESLint.RuleFix[]`) and this can be a little confuse, as we need to encapsulate the fixers in `arrays` and use `.concat` (which accepts either a single item or an `array`). See https://github.com/angular-eslint/angular-eslint/pull/501#discussion_r641589200.

In this PR, the proposal is to return `undefined` instead and whenever we use it, we call the` isNotNullOrUndefined` helper to extract only the valid fix from an `array`.

2021-06-07 13:10 UTC, JamesHenry requested changes
Please could we change it to be `null` to represent the intentional "non-useful" value? I feel it is a little more explicit (as an unintentional `undefined` return value is easily done)

2021-06-07 16:02 UTC, rafaelss95 commented
1. You mean that we should use `| null` instead? If so, no problem. I just opted by `| undefined` to conform to the rest of the methods.

2. While `null` is accepted, `Type '(RuleFix | null)[]' is not assignable to type 'RuleFix | RuleFix[] | IterableIterator<RuleFix> | null'.`, so we need to use a type-guard function to extract only truthy values from an array.

2021-06-11 10:58 UTC, JamesHenry commented
Thanks @rafaelss95 that makes sense!

2021-06-11 10:58 UTC, JamesHenry approved these changes

2021-06-11 11:17 UTC, merged